### ISSUE TITLE
Compiling instruction

### ISSUE THREAD

**Issue by andreacampanella** [xmm15/ZenithOS#1]
I would be happy to help, do you have any instructions how to compile it?

**Comment by xmm15** [comment]
Well, this repository is kind of a read-only thing. There is an ISO of the commit in the /src/Tmp folder, called "Zenith-Latest.iso". You can boot that in a VM and have at it with the source, as all the source is present on the distro. This is a fork of TempleOS after all! If you make some changes to the source, you could copy the relevant files into a folder, make a RedSea ISO, and grab that out of the VM's disk, and send it over to me as an issue or PR attachment, or even my email. I will make sure I flush out some instructions on contributing very soon.

**Comment by xmm15** [comment]
Contribution section added to README.
