### ISSUE TITLE
Isn't this sacrilege?

### ISSUE THREAD

**Issue by coldacid** [xmm15/ZenithOS#2]
Given the divine inspiration given to St Terry from GOD is it not a sin to make these changes? It implies that you know better than HIM and HIS ordained Prophet^H^H^H^Hgrammer, making such changes to TempleOS. You should cease and repent, lest Satan beckons you into his dark realm.

**Comment by Midnoclose** [comment]
Not related to the software itself.

**Comment by xmm15** [comment]
God approves.
![image](https://user-images.githubusercontent.com/58407827/75068473-db669100-54b4-11ea-809e-0ab1f4761022.png)
